# The first vertex on a face MUST be immediately to the left of the top vector of the text.
def create_d6
    p000 = Geom::Point3d.new((-0.5 * scale), (-0.5 * scale), (-0.5 * scale))
    p001 = Geom::Point3d.new((-0.5 * scale), (-0.5 * scale), ( 0.5 * scale))
    p010 = Geom::Point3d.new((-0.5 * scale), ( 0.5 * scale), (-0.5 * scale))
    p100 = Geom::Point3d.new(( 0.5 * scale), (-0.5 * scale), (-0.5 * scale))
    p011 = Geom::Point3d.new((-0.5 * scale), ( 0.5 * scale), ( 0.5 * scale))
    p101 = Geom::Point3d.new(( 0.5 * scale), (-0.5 * scale), ( 0.5 * scale))
    p110 = Geom::Point3d.new(( 0.5 * scale), ( 0.5 * scale), (-0.5 * scale))
    p111 = Geom::Point3d.new(( 0.5 * scale), ( 0.5 * scale), ( 0.5 * scale))

    f1 = d6_mesh.add_face([p011, p111, p110, p010])
    f2 = d6_mesh.add_face([p010, p110, p100, p000])
    f3 = d6_mesh.add_face([p011, p010, p000, p001])
    f4 = d6_mesh.add_face([p110, p111, p101, p100])
    f5 = d6_mesh.add_face([p111, p011, p001, p101])
    f6 = d6_mesh.add_face([p000, p100, p101, p001])

    tempNumberGroup = model.active_entities.add_group()
    faceCount = d6_mesh.length()
    counter = 1
    d6_mesh.first(faceCount).each do |face|
        if face.is_a? Sketchup::Face
            numberGroup = tempNumberGroup.entities.add_group()
            numberEntities = numberGroup.entities()
            numberEntities.add_3d_text(counter.to_s, TextAlignCenter, fontName, isBold, isItalic, letterHeight)
            numberBounds = numberGroup.bounds()
            numberEntities.transform_entities(getLetterPlanePlace(face, (numberBounds.width / 2) + fontOffsets[counter-1][0], (numberBounds.height / 2) + fontOffsets[counter-1][1], 0), numberEntities.to_a)
            counter += 1
        end
    end

end

========================================================================================================================

#(0..20).each() do |i|
#    create_glyph(name: i.to_s(), Util::MAIN_MODEL.entities(), Geom::Transformation.translation(Geom::Point3d::new(10*i, 0, 0)))
#end

========================================================================================================================

#ffheight means the height between diametric faces
#vvheight means the height between diametric vertices
#fvheight means the height between a face and its diametric vertex
#
#D20 ffheight = 20mm       vvheight = 24mm       font = 4.5mm
#D6  ffheight = 15mm       vvheight = 24mm       font = 8mm
#D8  ffheight = 15mm       vvheight = 24mm       font = 7mm
#D4  fvheight = 18mm                             font = 6mm
#D12 ffheight = 18.5mm     vvheight = 22mm       font = 6mm
#D10 ffheight = 16mm       vvheight = 23mm       font = 7mm      on a D% the smaller digit is 5mm and the large is 7mm
#
#(0..20).each() do |i|
#    create_glyph(name: i.to_s(), Util::MAIN_MODEL.entities(), Geom::Transformation.translation(Geom::Point3d::new(10*i, 0, 0)))
#end

========================================================================================================================

# ===== TODO =====
# Make a utility function for capturing groups and outputting them as models, so we can edit the geometric base shapes.
# And set the angle offsets for D% and D10 correctly.
# And also program all the other models in too.

I need to redo all the face orders and orientations and the die_scale factors.
Also also, we need to add comments to the die model classes saying their size specifications!
